# Generated by Django 4.2.6 on 2023-10-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_post_author_alter_profile_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
